/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#53433d',
        'surface-container-high': '#e9e8e2',
        'outline-variant': '#d9c2b9',
        'tertiary-fixed': '#e4e2e1',
        'surface-container-highest': '#e3e3dc',
        'on-background': '#1b1c18',
        'on-error': '#ffffff',
        'on-surface': '#1b1c18',
        'surface-tint': '#8e4d30',
        tertiary: '#5f5e5e',
        'primary-fixed': '#ffdbcd',
        background: '#fafaf3',
        'on-tertiary-container': '#2b2b2b',
        'on-tertiary-fixed-variant': '#474746',
        'primary-fixed-dim': '#ffb597',
        'secondary-container': '#e7e2d7',
        'tertiary-fixed-dim': '#c8c6c5',
        'tertiary-container': '#939292',
        'inverse-on-surface': '#f2f1ea',
        'on-primary': '#ffffff',
        secondary: '#615e56',
        'surface-container-low': '#f5f4ed',
        'inverse-primary': '#ffb597',
        'secondary-fixed': '#e7e2d7',
        'surface-bright': '#fafaf3',
        'primary-container': '#cc7f5e',
        'on-tertiary-fixed': '#1b1c1c',
        error: '#ba1a1a',
        'on-primary-fixed': '#360f00',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'on-secondary-fixed': '#1d1c15',
        'surface-container': '#efeee7',
        'inverse-surface': '#30312c',
        'on-primary-container': '#4e1b03',
        outline: '#86736c',
        'surface-variant': '#e3e3dc',
        'on-tertiary': '#ffffff',
        surface: '#fafaf3',
        primary: '#8e4d30',
        'secondary-fixed-dim': '#cbc6bc',
        'on-primary-fixed-variant': '#71361b',
        'surface-dim': '#dbdad4',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#49473f',
        'on-secondary-container': '#67645c',
        'error-container': '#ffdad6',
      },
      fontFamily: {
        headline: ['Noto Serif', 'serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}